# from app.api.yummy.utilities import (
#     create_recipe, update_recipe, create_category, update_category,
#     delete_recipe, register_user, user_login, delete_category
# )
# from app.exceptions import ResourceAlreadyExists, YouDontOwnResource
# from sqlalchemy.orm.exc import NoResultFound
# from tests.basetest import BaseTestCase


# class TestUtilities(BaseTestCase):
#     def test_create_recipe_raises_exceptions(self):
#         data = {
#             "name":"sample",
#             "description":"sample"
#         }  
#         usr_id = 1
#         ctg_id = 1
#         self.assertRaises(NoResultFound, create_recipe(data, ctg_id, usr_id))
#         self.assertRaises(ResourceAlreadyExists, create_recipe(data, ctg_id, usr_id))


#     def test_update_recipe_raises_exceptions(self):
        
#         self.assertRaises(NoResultFound, delete_recipe(1))
#         self.assertRaises(YouDontOwnResource, delete_recipe(1))

# #not pasiing yet

from app.api.yummy.utilities import (
#     create_recipe, update_recipe, create_category, update_category,
#     delete_recipe, register_user, user_login, delete_category
# )
# from app.exceptions import ResourceAlreadyExists, YouDontOwnResource
# from sqlalchemy.orm.exc import NoResultFound
# from tests.basetest import BaseTestCase


# class TestUtilities(BaseTestCase):
#     def test_create_recipe_raises_exceptions(self):
#         data = {
#             "name":"sample",
#             "description":"sample"
#         }  
#         usr_id = 1
#         ctg_id = 1
#         self.assertRaises(NoResultFound, create_recipe(data, ctg_id, usr_id))
#         self.assertRaises(ResourceAlreadyExists, create_recipe(data, ctg_id, usr_id))


#     def test_update_recipe_raises_exceptions(self):
        
#         self.assertRaises(NoResultFound, delete_recipe(1))
#         self.assertRaises(YouDontOwnResource, delete_recipe(1))

# #not pasiing yet





    



    